[2023-07-10T18:45:49.680+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:45:43.346703+00:00 [queued]>
[2023-07-10T18:45:49.698+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:45:43.346703+00:00 [queued]>
[2023-07-10T18:45:49.698+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T18:45:49.720+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_etl_users> on 2023-07-10 18:45:43.346703+00:00
[2023-07-10T18:45:49.732+0000] {standard_task_runner.py:57} INFO - Started process 767 to run task
[2023-07-10T18:45:49.739+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coin_api_dag', 'spark_etl_users', 'manual__2023-07-10T18:45:43.346703+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/coin_api.py', '--cfg-path', '/tmp/tmp6zwqo9q7']
[2023-07-10T18:45:49.743+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask spark_etl_users
[2023-07-10T18:45:49.832+0000] {task_command.py:410} INFO - Running <TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:45:43.346703+00:00 [running]> on host 123bc44f0e2f
[2023-07-10T18:45:49.999+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nahuelCasa' AIRFLOW_CTX_DAG_ID='coin_api_dag' AIRFLOW_CTX_TASK_ID='spark_etl_users' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T18:45:43.346703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T18:45:43.346703+00:00'
[2023-07-10T18:45:50.018+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-07-10T18:45:50.019+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py
[2023-07-10T18:45:50.182+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-10T18:45:53.208+0000] {spark_submit.py:490} INFO - Traceback (most recent call last):
[2023-07-10T18:45:53.209+0000] {spark_submit.py:490} INFO - File "/opt/***/scripts/apicalls.py", line 186, in <module>
[2023-07-10T18:45:53.209+0000] {spark_submit.py:490} INFO - main()
[2023-07-10T18:45:53.210+0000] {spark_submit.py:490} INFO - File "/opt/***/scripts/apicalls.py", line 174, in main
[2023-07-10T18:45:53.210+0000] {spark_submit.py:490} INFO - api = CoinApi()
[2023-07-10T18:45:53.211+0000] {spark_submit.py:490} INFO - File "/opt/***/scripts/apicalls.py", line 21, in __init__
[2023-07-10T18:45:53.212+0000] {spark_submit.py:490} INFO - self.url = config['API_URL']
[2023-07-10T18:45:53.213+0000] {spark_submit.py:490} INFO - KeyError: 'API_URL'
[2023-07-10T18:45:53.306+0000] {spark_submit.py:490} INFO - 23/07/10 18:45:53 INFO ShutdownHookManager: Shutdown hook called
[2023-07-10T18:45:53.316+0000] {spark_submit.py:490} INFO - 23/07/10 18:45:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-94754b7b-6ede-474d-bdf9-5959d3d500f0
[2023-07-10T18:45:53.404+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py. Error code is: 1.
[2023-07-10T18:45:53.413+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=coin_api_dag, task_id=spark_etl_users, execution_date=20230710T184543, start_date=20230710T184549, end_date=20230710T184553
[2023-07-10T18:45:53.441+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task spark_etl_users (Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py. Error code is: 1.; 767)
[2023-07-10T18:45:53.484+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T18:45:53.530+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
