[2023-07-10T18:39:13.908+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:39:07.419944+00:00 [queued]>
[2023-07-10T18:39:13.923+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:39:07.419944+00:00 [queued]>
[2023-07-10T18:39:13.923+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T18:39:13.944+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_etl_users> on 2023-07-10 18:39:07.419944+00:00
[2023-07-10T18:39:13.950+0000] {standard_task_runner.py:57} INFO - Started process 497 to run task
[2023-07-10T18:39:13.955+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coin_api_dag', 'spark_etl_users', 'manual__2023-07-10T18:39:07.419944+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/coin_api.py', '--cfg-path', '/tmp/tmprtz3qgxh']
[2023-07-10T18:39:13.958+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask spark_etl_users
[2023-07-10T18:39:14.046+0000] {task_command.py:410} INFO - Running <TaskInstance: coin_api_dag.spark_etl_users manual__2023-07-10T18:39:07.419944+00:00 [running]> on host 123bc44f0e2f
[2023-07-10T18:39:14.199+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nahuelCasa' AIRFLOW_CTX_DAG_ID='coin_api_dag' AIRFLOW_CTX_TASK_ID='spark_etl_users' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T18:39:07.419944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T18:39:07.419944+00:00'
[2023-07-10T18:39:14.218+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-07-10T18:39:14.221+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py
[2023-07-10T18:39:14.385+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-10T18:39:18.206+0000] {spark_submit.py:490} INFO - Traceback (most recent call last):
[2023-07-10T18:39:18.207+0000] {spark_submit.py:490} INFO - File "/opt/***/scripts/apicalls.py", line 172, in <module>
[2023-07-10T18:39:18.207+0000] {spark_submit.py:490} INFO - coin_api = CoinApi()
[2023-07-10T18:39:18.208+0000] {spark_submit.py:490} INFO - File "/opt/***/scripts/apicalls.py", line 21, in __init__
[2023-07-10T18:39:18.208+0000] {spark_submit.py:490} INFO - self.url = config['API_URL']
[2023-07-10T18:39:18.209+0000] {spark_submit.py:490} INFO - KeyError: 'API_URL'
[2023-07-10T18:39:18.296+0000] {spark_submit.py:490} INFO - 23/07/10 18:39:18 INFO ShutdownHookManager: Shutdown hook called
[2023-07-10T18:39:18.301+0000] {spark_submit.py:490} INFO - 23/07/10 18:39:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-c2988240-5ade-4abf-b62e-0b6e70691ce4
[2023-07-10T18:39:18.392+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py. Error code is: 1.
[2023-07-10T18:39:18.401+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=coin_api_dag, task_id=spark_etl_users, execution_date=20230710T183907, start_date=20230710T183913, end_date=20230710T183918
[2023-07-10T18:39:18.425+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 26 for task spark_etl_users (Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/apicalls.py. Error code is: 1.; 497)
[2023-07-10T18:39:18.449+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T18:39:18.484+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
